### PR TITLE
권한 테스트

### PR DESCRIPTION
**Pull request by ttkmw**
## Related Issue

resolve: #*(Write down your issue number)*

## Description

*(Write down your details)*

## Checklist

Thank you for your contribution.
Before submitting this PR, please make sure:

- [ ] Test case
- [ ] End of Work

### CODE REVIEW

**Comment by als95** [comment]
테스트

**Review by pingoo33 — APPROVED** [review]
테스트

**Review by pingoo33 — APPROVED** [review]
테스트2

**Review by pingoo33 — COMMENTED** [review]
테스트

**Pull request closed without merging**
